### ISSUE TITLE
Screen stays blank after a visit to the menus

### ISSUE THREAD

**Issue by xmacex** [justmat/massif#1]
Servus

After any visit to the menus with <kbd>K1</kbd> the screen stays blank on return, rather than showing the UI. Other commands such as changing mode with <kbd>K1</kbd>+<kbd>K2</kbd>/<kbd>K3</kbd> or the values with encoders in edit mode works.

If I manually set `dirty = true` after making it a global variable, screen refresh happens. I am trying to figure out why https://github.com/justmat/massif/blob/32d7feb14d1c0b84109e4e76e72767731b679efb/massif.lua#L180 doesn't set it, it is unconditional within the `key` function.

![main-qimg-b144481da52c8c95403eefa75bc3594b-lq](https://github.com/justmat/massif/assets/879300/8e0ca627-3b29-40c5-a3a4-0feacdfc9b26)

**Comment by xmacex** [comment]
I just noticed that a long press (maybe ¼ second) on <kbd>K1</kbd> after arrival from menus redraws the screen.

**Comment by justmat** [comment]
hmmmmm, i will give it a once over tonight! thanks for the heads up :D

**Comment by xmacex** [comment]
I am currently looking if I can find a fix, and will pass a PR if I do.

**Comment by xmacex** [comment]
A quick tap on the <kbd>K1</kbd> simply does not run `key` but instead jumps to the menus. A longer press is needed, I am thinking if there is a way to detect when we have been to the menus and are back from them... 🤔 💭  something something remember `_menu.mode` maybe?

**Comment by xmacex** [comment]
Funny, if you sneak a `print("yodelidoo")` in the top of `redraw` say on [line 238](https://github.com/justmat/massif/blob/32d7feb14d1c0b84109e4e76e72767731b679efb/massif.lua#L238), it stops printing when you enter the menus, and yields a

```
metro_stop(): pthread_cancel() failed; error: 
specified thread does not exist
```

However if you sneak it [on 141](https://github.com/justmat/massif/blob/32d7feb14d1c0b84109e4e76e72767731b679efb/massif.lua#L141) in front of call to `redraw`, it keeps printing while in the menus.

**Comment by justmat** [comment]
haha, i was wondering about the same thing. i even asked on the norns study group about a way to tell if the user has returned from the menu! i seem to remember there being something, but i haven't located it yet

**Comment by xmacex** [comment]
I think i have a fix, now testing.
